name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@v1
        with:
          token: ${{ secrets.PR_STATS_TOKEN}}
          period: 30
          charts: true
          sort-by: 'COMMENTS'
